In [57]:
import numpy as np
from numpy.polynomial import Polynomial
from sympy import symbols, simplify, Poly, Matrix
from sympy.abc import x, y, z
from scipy import linalg
import random
import galois

GF = galois.GF(2)

l=3
m=2
n=m*l
a = [random.randint(0,1) for i in range(n**2)]
a = [[1,0,1], [1,1,0]]
x = np.array(a).reshape(2, 3)

print(x)
print(linalg.null_space(x))
A = GF(x)
A.null_space()




[[1 0 1]
 [1 1 0]]
[[-0.57735027]
 [ 0.57735027]
 [ 0.57735027]]


GF([[1, 1, 1]], order=2)

In [1]:
import pickle

In [73]:
with open('zaratan/3.18/save/count.pkl', 'rb') as f:
    count = pickle.load(f)
    print(count)

740000


In [4]:
from queue import Queue
a=Queue()
a.put(1)
a.put(2)
a.qsize()

2

In [8]:
import itertools

stuff = [1, 2, 3, 4]
combinations = list(itertools.combinations(stuff, 2))

# Print the list of combinations to the console
print(combinations)
combinations.index((2,4))


[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


4

/scratch/zt1/project/xiaodiwu-prj/user/hwdeng/QECC_Synth/

| 角色 | 时间 | 链接 |
|:---:|:---:|:----:|

In [2]:
def numberToBase(n, b):
    if n == 0:
        return [0]
    digits = []
    while n:
        digits.append(int(n % b))
        n //= b
    return digits[::-1]

numberToBase(11, 4)

[2, 3]

In [21]:
import numpy as np

a=12
n=6
f'{a:0{n}b}'
# a= np.array([-1,-2,3,4])
# np.where(np.absolute(a)>2)[0]

'001100'

In [4]:
from itertools import product

list(product([1,2], [3,4], [5,6]))



[(1, 3, 5),
 (1, 3, 6),
 (1, 4, 5),
 (1, 4, 6),
 (2, 3, 5),
 (2, 3, 6),
 (2, 4, 5),
 (2, 4, 6)]

In [63]:
enumerator = get_enum_tensor(code603, 1) 
for d in enumerator:
    display(d)


length: 64


Polynomial([1., 0., 0., 4., 7., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 0., 6., 8., 2.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

In [36]:
a=set()
a.add((1,0.5))
a.add(2,0.4)

[(1, 3), (1, 6), (2, 3), (2, 6), (3, 3), (3, 6), (4, 3), (4, 6)]

In [13]:

x=0.01
z=0.05
y=x*z
i = 1-x-y-z
i*y*z*z*x

1.174375e-08

A=x0+y8+y10, B=x1+x2+y9
l=3,m=15,k=8,d=10 

A=x1+x5+y3, B=x3+y1+y2
l=6,m=9,k=8,d=10
...


$\sum a_i a_j$,    where $i,j$ has $ v_i, v_j \in V$ and $(v_i, v_j) \in E$. 


$$
\sum_{l,m} \frac{kd}{n}

$$

In [11]:

(l=18,m=3), [[108, 12, 6]], x0+x3+y1, x6+x9+y2

1.0946185593750002e-08

2 x^3 y + 2 x^2 y^2 + 2 x^2 z^2 + 6 x y z^2 + y^4 + 2 y^2 z^2 + 1
5 x^2 y^2 + 5 x^2 z^2 + 5 y^2 z^2 + 1

In [ ]:
1 2 3 4 5
edge = [(1,3), (4,2)]

initTN = ([1],[])
TN = ([1,2], [[(1,0), (2,1)]])

def EdgeScore(TN, edge):
    score = 0
    if TN[0][0]==1 and edge[0][1]==1:
        score += 0.1
    ...
    return score

for edge in valid_edge:
    scores = [priority(TN, edge)]
    better_edge = max(scores)

def Sift(A, l, m):
    A1, A2, A3 = A[0], A[1], A[2]
    if (A1[0],A2[0],A3[0])==('x','y','y'):
        if A2[1]+A3[1]==m:
            return True
    ...
    return False

for A in candidate_A:
    if Sift(A,l,m)==False:
        continue
    for B in candidate_B:
        evaluate(QC(A,B,l,m))


def DFS(TN, edge):
    if TN.size >= SIZE_LIMIT:
        return
    TN.add(edge)
    evaluate(TN)
    edges = get_all_edges(TN)
    sort(edges, 
        key=lambda edge: score(edge),
        reversed=True)
    for edge in edges:
        DFS(TN, edge)
