In [1]:
import numpy as np
from numpy.polynomial import Polynomial
from sympy import symbols, simplify, Poly
from sympy.abc import x, y, z

x = np.arange(9.).reshape(3, 3)
y = np.zeros((3,3))
print(x)
#set the first 10 rows of cols 1,2 to be zero
y[3:, :] = x[3:, :]
print(y[3:, :])


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[]


In [8]:
def numberToBase(n, b):
    if n == 0:
        return [0]
    digits = []
    while n:
        digits.append(int(n % b))
        n //= b
    return digits[::-1]

numberToBase(11, 4)

[2, 3]

In [24]:

p2 = Poly(x*y + x - 3 + 2*x**2 - z*x**2 + x**3, domain='R')
p1 = x*y + x - 3 + 2*x**2 - z*x**2 + x**3

p1.subs({x:0.01, z:0.05, y:0.1})

-2.98880400000000

In [25]:
from enumerator import *

isinstance(1,int)

True

In [63]:
enumerator = get_enum_tensor(code603, 1) 
for d in enumerator:
    display(d)


length: 64


Polynomial([1., 0., 0., 4., 7., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 0., 6., 8., 2.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

In [36]:
a=set()
a.add((1,0.5))
a.add(2,0.4)

[(1, 3), (1, 6), (2, 3), (2, 6), (3, 3), (3, 6), (4, 3), (4, 6)]