In [57]:
import numpy as np
from numpy.polynomial import Polynomial
from sympy import symbols, simplify, Poly, Matrix
from sympy.abc import x, y, z
from scipy import linalg
import random
import galois

GF = galois.GF(2)

l=3
m=2
n=m*l
a = [random.randint(0,1) for i in range(n**2)]
a = [[1,0,1], [1,1,0]]
x = np.array(a).reshape(2, 3)

print(x)
print(linalg.null_space(x))
A = GF(x)
A.null_space()




[[1 0 1]
 [1 1 0]]
[[-0.57735027]
 [ 0.57735027]
 [ 0.57735027]]


GF([[1, 1, 1]], order=2)

In [1]:
import pickle

In [73]:
with open('zaratan/3.18/save/count.pkl', 'rb') as f:
    count = pickle.load(f)
    print(count)

740000


In [75]:
a,b = (1,2)
a

1

/scratch/zt1/project/xiaodiwu-prj/user/hwdeng

| 角色 | 时间 | 链接 |
|:---:|:---:|:----:|

In [8]:
def numberToBase(n, b):
    if n == 0:
        return [0]
    digits = []
    while n:
        digits.append(int(n % b))
        n //= b
    return digits[::-1]

numberToBase(11, 4)

[2, 3]

In [24]:

p2 = Poly(xy + x - 3 + 2x^2 - zx^2 + x^3, domain='R')
p1 = xy + x - 3 + 2x^2 - zx^2 + x^3

p1.subs({x:0.01, z:0.05, y:0.1})

-2.98880400000000

In [25]:
from enumerator import 

isinstance(1,int)

True

In [63]:
enumerator = get_enum_tensor(code603, 1) 
for d in enumerator:
    display(d)


length: 64


Polynomial([1., 0., 0., 4., 7., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 0., 6., 8., 2.], domain=[-1.,  1.], window=[-1.,  1.])

Polynomial([0., 0., 2., 4., 6., 4.], domain=[-1.,  1.], window=[-1.,  1.])

In [36]:
a=set()
a.add((1,0.5))
a.add(2,0.4)

[(1, 3), (1, 6), (2, 3), (2, 6), (3, 3), (3, 6), (4, 3), (4, 6)]

In [13]:

x=0.01
z=0.05
y=x*z
i = 1-x-y-z
i*y*z*z*x

1.174375e-08

In [11]:
y*x*z**2*(1-x)**3*(1-z)**25

1.0946185593750002e-08

2 x^3 y + 2 x^2 y^2 + 2 x^2 z^2 + 6 x y z^2 + y^4 + 2 y^2 z^2 + 1
5 x^2 y^2 + 5 x^2 z^2 + 5 y^2 z^2 + 1

In [ ]:
1 2 3 4 5
edge = [(1,3), (4,2)]

initTN = ([1],[])
TN = ([1,2], [[(1,0), (2,1)]])

def priority(TN, edge):
    score = 0
    if TN[0][0]==1 and edge[0][1]==1:
        score += 0.1
    ...
    return score

for edge in valid_edge:
    scores = [priority(TN, edge)]
    better_edge = max(scores)
